### ISSUE TITLE
One global fault means a second client consumes another test's after/count

### ISSUE THREAD

**Issue by armaatus** [armaatus/rommsync-nx#118]
Found on 2026-09-06 by running two ctest processes against one RomM deliberately, while testing a different hypothesis.

`server/testing/fault_proxy.py` holds ONE global armed scenario — `FAULT = Fault()` (`:99-150`). `arm()` overwrites unconditionally, and `claim()` counts every matching request regardless of who made it.

`after:N` and `count:N` are therefore counters over *all* traffic through the proxy, not over the arming client's traffic. A second client consumes them, so the fault fires on a stranger's request and the test that armed it never sees it.

The signature is a confusing red in a test that looks unrelated to whatever else was running:

```
FAIL: two failed polls and the one that worked -- expected 3, got 2
```

Observed across `pair.retry`, `pair.stall`, `tick.upload_*`, `tick.download_*` and `complete.unchanged` — every one of them a test armed with a *positional* fault. Tests that arm a fault with no `after`/`count` position are unaffected.

**`RUN_SERIAL` does not protect against this.** It orders tests within one ctest invocation and says nothing about a second invocation, and the proxy has no idea who armed a fault. This is worth stating in the file, because `RUN_SERIAL` is currently carrying an implication it cannot support.

**Scope:** give a fault an owner. Either scope it to an arming token the client sends back on its requests, or refuse to arm over a fault somebody else armed and say so loudly. Whichever is chosen, the failure should name the real cause rather than surfacing as an off-by-one in an unrelated assertion.

**Not in scope:** #109, the stall that forwards after its client has gone. Same file, different defect, and they should not be tangled.

**Acceptance:** with two clients through one proxy, a positional fault armed by one is not consumed by the other; a test covers it; the `RUN_SERIAL` comments that imply isolation are corrected.

**Seen again on 2026-09-06, from #43's worktree, and it is the same mechanism
rather than a new one.** Four full-suite runs produced one red each --
`ipc.engine`, then `sync.stalled`, then `engine.repairs`, then `engine.pairs` --
four different tests, four different runs, every one of them green in isolation
on the next attempt. (`engine.pairs` came later than the other three and was
missed when this paragraph was first written; it is the same shape.) Two of the three coincided with a second `ctest` running against the
same proxy: a review subagent was verifying the same branch concurrently and
said so. That is exactly the two-clients-one-proxy case above, and it is worth
recording that the symptom is not always the off-by-one assertion quoted here --
`engine.repairs`, `engine.pairs` and `ipc.engine` are pairing tests that arm
positional faults and fail with a timeout instead, which is what a fault consumed
by a stranger looks like from the side that was waiting for it. Three of the four
presented that way, so the signature quoted above matches only one of them.

The practical consequence for anyone reading this before it is fixed: a single
red in an otherwise green full-suite run is not evidence of anything until it has
been re-run alone. Both the automated review and the local verification loop run
`ctest` while an agent may also be running one.

---

**Resolved by scoping, not by refusing to arm.** Of the two options in Scope,
the arming token is the one that holds: refusing to arm over somebody else's
fault would still leave two concurrent `ctest` runs unable to both work, and it
answers the wrong half of the acceptance ("not consumed by the other"). The
proxy now keys its armed scenarios by an `X-Fault-Owner` tag, `tests/rig.hpp`
mints one per process and signs every proxy-bound request with it, and an
untagged scenario stays global so the documented one-line `curl` still works.

**Two clients through one proxy is not the only way a second `ctest` breaks the
first — see #151.** Every rig binary downloads into one shared
`build/tests/scratch` under fixed names, so two invocations clobber each other's
files whatever the proxy does. That is a separate mechanism on disk rather than
in the proxy, and it is filed rather than fixed here. Anyone re-reading the four
reds recorded above should treat #151 as a candidate explanation for the ones
that touched downloads.

**Comment by armaatus** [comment]
Seen again while finishing M1-6 (#123), which is a fresh data point rather than a
new diagnosis: `pair.retry` failed inside a `ctest -R "engine|pair\."` run and
**passed on its own seconds later, unchanged**, while a second worktree (#31) was
running its own suite against its own RomM through its own proxy port.

Worth noting because it narrows nothing and widens one thing: the two worktrees
have different `PROXY_BASE_URL`s, so this was not two clients sharing one proxy
in the way the issue title describes. The contention that remains is the host —
both suites were running `RUN_SERIAL` scenarios at once, and `pair.retry`'s
assertions are about *timing* (a 5xx mid-poll must back off and not abandon a
live code), so a scenario that waits out real poll intervals under load is the
shape most likely to go red for no reason.

Whatever the fix here ends up being, a flake that only ever reproduces under
cross-worktree load is one this repo will keep meeting: `./scripts/orca/fleet.sh`
runs three at a time by design.
